{{- if .Values.serviceAccount.create -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "finance-api.fullname" . }}
  labels:
    {{- include "finance-api.labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  defaultAddCapabilities:
  - CHOWN
  - NET_BIND_SERVICE
  - SETGID
  - SETUID
  - DAC_OVERRIDE
  requiredDropCapabilities:
  - ALL
  volumes:
  - persistentVolumeClaim
  - secret
  - configMap
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "finance-api.fullname" . }}
  labels:
    {{- include "finance-api.labels" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - {{ include "finance-api.fullname" . }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "finance-api.fullname" . }}
  labels:
    {{- include "finance-api.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "finance-api.serviceAccountName" .  }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "finance-api.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
