apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "finance-api.fullname" . }}
  labels:
    {{- include "finance-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
