apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finance-api.fullname" . }}
  labels:
    {{- include "finance-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | required "A valid .secretKeyBase is required. See https://guides.rubyonrails.org/security.html#custom-credentials for more details" }}
