apiVersion: v1
kind: Service
metadata:
  name: {{ include "finance-api.fullname" . }}
  labels:
    {{- include "finance-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "finance-api.selectorLabels" . | nindent 4 }}
